---
name: Testing and linting

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '35 8 * * 6'

jobs:
  extension-test:
    name: 'Testing and linting'
    uses: astehlik/typo3-extension-buildtools/.github/workflows/extension-test.yml@TYPO3_14

  extension-qltysh-coverage:
    name: 'Qlty coverage'
    uses: astehlik/typo3-extension-buildtools/.github/workflows/extension-qltysh-coverage.yml@TYPO3_14
    if: github.ref == 'refs/heads/develop'
    secrets:
      QLTY_COVERAGE_TOKEN: ${{ secrets.QLTY_COVERAGE_TOKEN }}
